// generated by src/lib/gro_builtin_tasks.gen.ts - DO NOT EDIT DIRECTLY!

import type * as build_task from './build.task.ts';
import type * as changeset_task from './changeset.task.ts';
import type * as check_task from './check.task.ts';
import type * as clean_task from './clean.task.ts';
import type * as commit_task from './commit.task.ts';
import type * as deploy_task from './deploy.task.ts';
import type * as dev_task from './dev.task.ts';
import type * as format_task from './format.task.ts';
import type * as gen_task from './gen.task.ts';
import type * as lint_task from './lint.task.ts';
import type * as publish_task from './publish.task.ts';
import type * as reinstall_task from './reinstall.task.ts';
import type * as release_task from './release.task.ts';
import type * as resolve_task from './resolve.task.ts';
import type * as run_task from './run.task.ts';
import type * as sync_task from './sync.task.ts';
import type * as test_task from './test.task.ts';
import type * as typecheck_task from './typecheck.task.ts';
import type * as upgrade_task from './upgrade.task.ts';

/**
 * Gro's builtin tasks by name, mapped to their module types.
 */
export interface GroBuiltinTasks {
	build: typeof build_task;
	changeset: typeof changeset_task;
	check: typeof check_task;
	clean: typeof clean_task;
	commit: typeof commit_task;
	deploy: typeof deploy_task;
	dev: typeof dev_task;
	format: typeof format_task;
	gen: typeof gen_task;
	lint: typeof lint_task;
	publish: typeof publish_task;
	reinstall: typeof reinstall_task;
	release: typeof release_task;
	resolve: typeof resolve_task;
	run: typeof run_task;
	sync: typeof sync_task;
	test: typeof test_task;
	typecheck: typeof typecheck_task;
	upgrade: typeof upgrade_task;
}
