import type { Args } from '@fuzdev/fuz_util/args.ts';
import { fs_search } from '@fuzdev/fuz_util/fs.ts';
import type { PathFilter, PathId } from '@fuzdev/fuz_util/path.ts';
import { ensure_end, strip_start } from '@fuzdev/fuz_util/string.ts';
import { dirname, relative } from 'node:path';
import type { z } from 'zod';

import type { GenConfig } from './gen.ts';
import type { GroBuiltinTasks } from './gro_builtin_tasks.ts';
import { GRO_DIST_DIR } from './paths.ts';
import { is_task_path, to_task_name } from './task.ts';

/**
 * The project's own tasks by name, empty until augmented by a generated file.
 * Create a genfile like `src/gro_tasks.gen.ts` exporting `gen_task_registry` as `gen`
 * to type the project's task names and args for `invoke_task`.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface ProjectTasks {}

/**
 * Every task name `invoke_task` accepts as a literal, mapped to its module's type.
 * Mirrors runtime resolution: a project task shadows the builtin with the same name,
 * and `gro/`-prefixed names always reach the builtin.
 */
export type TaskRegistry = Omit<GroBuiltinTasks, keyof ProjectTasks> &
	ProjectTasks & {
		[K in keyof GroBuiltinTasks as `gro/${K & string}`]: GroBuiltinTasks[K];
	};

export type TaskName = Extract<keyof TaskRegistry, string>;

/**
 * The input type of the task's `Args` schema, so defaulted args are optional,
 * or loose `Args` for a task module without an `Args` export.
 */
export type TaskArgsInput<TName extends TaskName> = TaskRegistry[TName] extends {
	Args: infer TSchema extends z.ZodType;
}
	? z.input<TSchema>
	: Args;

export interface TaskRegistryEntry {
	name: string;
	id: PathId;
}

/**
 * Finds the tasks in `task_root_dirs` with the names runtime resolution gives them,
 * skipping Gro's builtins, which `GroBuiltinTasks` types.
 * A file or name found under an earlier root dir shadows later ones, like resolution.
 */
export const task_registry_find = async (
	task_root_dirs: Array<PathId>,
	search_filters: Array<PathFilter>
): Promise<Array<TaskRegistryEntry>> => {
	const entries: Map<string, TaskRegistryEntry> = new Map();
	const ids: Set<PathId> = new Set();
	for (const task_root_dir of task_root_dirs) {
		const dir = ensure_end(task_root_dir, '/');
		if (dir.startsWith(GRO_DIST_DIR)) continue;
		const found = await fs_search(dir, { filter: search_filters, file_filter: is_task_path });
		for (const { id } of found) {
			// a root dir like `./` also reaches Gro's dist, which the default search filters allow
			if (
				ids.has(id) ||
				id.startsWith(GRO_DIST_DIR) ||
				strip_start(id, dir).includes('node_modules/')
			)
				continue;
			ids.add(id);
			// a non-absolute input path names it relative to its root dir, like `gro` lists it
			const name = to_task_name(id, dir, '', '');
			if (!entries.has(name)) entries.set(name, { name, id });
		}
	}
	return Array.from(entries.values()).sort((a, b) => a.name.localeCompare(b.name));
};

const IDENTIFIER_MATCHER = /^[A-Za-z_$][\w$]*$/;

const render_key = (name: string): string =>
	IDENTIFIER_MATCHER.test(name) ? name : JSON.stringify(name);

/**
 * Renders the type-only imports of the task modules and their registry properties,
 * with import specifiers relative to `dir`, where the rendered file is written.
 */
const render_entries = (
	entries: Array<TaskRegistryEntry>,
	dir: PathId,
	indent: string
): { imports: string; properties: string } => {
	const used: Set<string> = new Set();
	let imports = '';
	let properties = '';
	for (const { name, id } of entries) {
		const base = name.replace(/[^\w$]/g, '_').replace(/^\d/, '_$&') + '_task'; // a valid identifier
		let identifier = base;
		for (let i = 2; used.has(identifier); i++) identifier = base + i;
		used.add(identifier);
		let specifier = relative(dir, id);
		if (!specifier.startsWith('.')) specifier = './' + specifier;
		imports += `import type * as ${identifier} from '${specifier}';\n`;
		properties += `${indent}${render_key(name)}: typeof ${identifier};\n`;
	}
	return { imports, properties };
};

/**
 * Renders the module augmentation of `ProjectTasks` written by `gen_task_registry`.
 */
export const task_registry_render_project = (
	entries: Array<TaskRegistryEntry>,
	output_dir: PathId,
	origin_path: string
): string => {
	const { imports, properties } = render_entries(entries, output_dir, '\t\t');
	return `// generated by ${origin_path} - DO NOT EDIT DIRECTLY!
// types the project's tasks for \`invoke_task\`, see \`@fuzdev/gro/task_registry.ts\`

${imports}
declare module '@fuzdev/gro/task_registry.ts' {
	interface ProjectTasks {
${properties}	}
}
`;
};

/**
 * Renders the `GroBuiltinTasks` interface for Gro's own tasks.
 */
export const task_registry_render_builtins = (
	entries: Array<TaskRegistryEntry>,
	output_dir: PathId,
	origin_path: string
): string => {
	const { imports, properties } = render_entries(entries, output_dir, '\t');
	return `// generated by ${origin_path} - DO NOT EDIT DIRECTLY!

${imports}
/**
 * Gro's builtin tasks by name, mapped to their module types.
 */
export interface GroBuiltinTasks {
${properties}}
`;
};

/**
 * The genfile config that types a project's tasks for `invoke_task`.
 * Export it as `gen` from a genfile like `src/gro_tasks.gen.ts`,
 * which writes `src/gro_tasks.ts` augmenting `ProjectTasks`.
 * Regenerates when a task file changes, so added and removed tasks are picked up.
 */
export const gen_task_registry: GenConfig = {
	generate: async ({ config, origin_id, origin_path }) => {
		const entries = await task_registry_find(config.task_root_dirs, config.search_filters);
		return task_registry_render_project(entries, dirname(origin_id), origin_path);
	},
	dependencies: { patterns: [/\.task\.(ts|js)$/] }
};
